// react-example/src/components/Status.js
import React, { useEffect, useState } from 'react';
import axios from 'axios';

const Status = () => {
  const [data, setData] = useState(null);

  useEffect(() => {
    axios.get('https://your-swagger-api-endpoint/status')
      .then(response => setData(response.data))
      .catch(error => console.error('Error fetching data:', error));
  }, []);

  return (
    <div>
      <h1>Status Page</h1>
      {data && <pre>{JSON.stringify(data, null, 2)}</pre>}
    </div>
  );
};

export default Status;

// vue-example/src/components/Status.vue
<template>
  <div>
    <h1>Status Page</h1>
    <pre>{{ data }}</pre>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'Status',
  data() {
    return {
      data: null
    };
  },
  created() {
    axios.get('https://your-swagger-api-endpoint/status')
      .then(response => {
        this.data = response.data;
      })
      .catch(error => {
        console.error('Error fetching data:', error);
      });
  }
};
</script>
