// angular-example/src/app/submit-data/submit-data.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-submit-data',
  template: `
    <h1>Submit Data Page</h1>
    <form (submit)="handleSubmit($event)">
      <label>
        Field:
        <input type="text" name="field" [(ngModel)]="formData.field" />
      </label>
      <button type="submit">Submit</button>
    </form>
  `
})
export class SubmitDataComponent {
  formData = { field: '' };

  constructor(private http: HttpClient) { }

  handleSubmit(event: Event) {
    event.preventDefault();
    this.http.post('https://your-swagger-api-endpoint/submit', this.formData)
      .subscribe(response => alert('Data submitted successfully'), error => console.error('Error submitting data:', error));
  }
}

// vue-example/src/components/SubmitData.vue
<template>
  <div>
    <h1>Submit Data Page</h1>
    <form @submit.prevent="handleSubmit">
      <label>
        Field:
        <input type="text" v-model="formData.field" />
      </label>
      <button type="submit">Submit</button>
    </form>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'SubmitData',
  data() {
    return {
      formData: { field: '' }
    };
  },
  methods: {
    handleSubmit() {
      axios.post('https://your-swagger-api-endpoint/submit', this.formData)
        .then(response => alert('Data submitted successfully'))
        .catch(error => console.error('Error submitting data:', error));
    }
  }
};
</script>
