// angular-example/src/app/status/status.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-status',
  template: `
    <h1>Status Page</h1>
    <pre>{{ data | json }}</pre>
  `
})
export class StatusComponent implements OnInit {
  data: any;

  constructor(private http: HttpClient) { }

  ngOnInit() {
    this.http.get('https://your-swagger-api-endpoint/status')
      .subscribe(response => this.data = response, error => console.error('Error fetching data:', error));
  }
}

// react-example/src/components/Status.js
import React, { useEffect, useState } from 'react';
import axios from 'axios';

const Status = () => {
  const [data, setData] = useState(null);

  useEffect(() => {
    axios.get('https://your-swagger-api-endpoint/status')
      .then(response => setData(response.data))
      .catch(error => console.error('Error fetching data:', error));
  }, []);

  return (
    <div>
      <h1>Status Page</h1>
      {data && <pre>{JSON.stringify(data, null, 2)}</pre>}
    </div>
  );
};

export default Status;
